version: "3.8"

services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS}
      - API_URL=${API_URL:-http://localhost:4000}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    working_dir: /app
    command: npm run dev
    networks:
      - alohawaii-network

networks:
  alohawaii-network:
    external: true
